/** @type {import('tailwindcss').Config} */
module.exports = {
	theme: {
		extend: {
			colors: {
				"primary": "#004ac6",
				"on-surface-variant": "#434655",
				"secondary-fixed": "#d9e3f6",
				"on-error": "#ffffff",
				"on-tertiary": "#ffffff",
				"secondary": "#555f6f",
				"secondary-container": "#d6e0f3",
				"on-secondary-fixed": "#121c2a",
				"on-secondary-container": "#596373",
				"outline-variant": "#c3c6d7",
				"tertiary-fixed-dim": "#c0c6db",
				"on-tertiary-fixed-variant": "#404758",
				"on-error-container": "#93000a",
				"primary-container": "#2563eb",
				"inverse-primary": "#b4c5ff",
				"error-container": "#ffdad6",
				"surface-dim": "#d9dadc",
				"surface-container-lowest": "#ffffff",
				"on-tertiary-container": "#ecf0ff",
				"outline": "#737686",
				"background": "#f9f9fb",
				"surface-container": "#eeeef0",
				"surface": "#f9f9fb",
				"on-tertiary-fixed": "#141b2b",
				"primary-fixed": "#dbe1ff",
				"inverse-on-surface": "#f0f0f2",
				"tertiary-fixed": "#dce2f7",
				"error": "#ba1a1a",
				"on-primary": "#ffffff",
				"surface-container-high": "#e8e8ea",
				"on-surface": "#1a1c1d",
				"surface-container-highest": "#e2e2e4",
				"on-secondary": "#ffffff",
				"tertiary-container": "#666d7f",
				"surface-container-low": "#f3f3f5",
				"primary-fixed-dim": "#b4c5ff",
				"on-primary-fixed-variant": "#003ea8",
				"on-primary-fixed": "#00174b",
				"inverse-surface": "#2f3132",
				"on-primary-container": "#eeefff",
				"surface-bright": "#f9f9fb",
				"surface-tint": "#0053db",
				"secondary-fixed-dim": "#bdc7d9",
				"tertiary": "#4e5566",
				"on-secondary-fixed-variant": "#3d4756",
				"on-background": "#1a1c1d",
				"surface-variant": "#e2e2e4",
			},
			fontFamily: {
				"headline": ["Inter", "sans-serif"],
				"body": ["Inter", "sans-serif"],
				"label": ["Inter", "sans-serif"],
			},
			borderRadius: {
				DEFAULT: "0.25rem",
				md: "0.75rem",
				lg: "0.5rem",
				xl: "1.5rem",
				full: "9999px",
			},
		},
	},
	plugins: [],
	content: [
		"./components/**/*.{js,vue,ts}",
		"./layouts/**/*.vue",
		"./pages/**/*.vue",
		"./plugins/**/*.{js,ts}",
		"./app.vue",
		"./error.vue",
	],
};
